default:
	g++ plotSIG.cxx -I/usr/include/root/\
    -L/usr/lib/i386-linux-gnu/ -lCore -lCint -lRIO -lNet -lHist\
    -lGraf -lGraf3d -lGpad -lTree -lRint -lPostscript -lSpectrum\
    -lMatrix -lPhysics -lMathCore -lThread -pthread -lm -ldl -rdynamic\
    -o plotSIG

clean:
	rm plotSIG
